import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { Miniflare, convertV4MiniflareOptions } from 'miniflare';
const service = await import('../worker/src/raising.mjs').catch(e => { if(e.code==='ERR_MODULE_NOT_FOUND') return {}; throw e; });
async function setup(t) {
  const mf = new Miniflare(convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("ok")}}',compatibilityDate:'2026-01-01',d1Databases:['DB']}));
  t.after(()=>mf.dispose());
  const DB=await mf.getD1Database('DB');
  await DB.exec('CREATE TABLE users (id TEXT PRIMARY KEY); INSERT INTO users VALUES ("alice"),("bob");');
  await DB.exec(await readFile(new URL('../worker/migrations/0004_raising.sql',import.meta.url),'utf8'));
  return {DB};
}
const req=(path,body)=>new Request(`https://test/api/raising/${path}`,body===undefined?{}:{method:'POST',body:JSON.stringify(body)});
const call=(env,path,body,user='alice')=>service.handleRaising(req(path,body),env,{id:user});
const bars=()=>Array.from({length:90},(_,i)=>({time:(Math.floor(Date.now()/60000)-90+i)*60,open:100+i,high:102+i,low:99+i,close:101+i,volume:10}));
test('malformed history cannot omit OHLC fields or accept non-finite data',async t=>{
  const env={...await setup(t),RAISING_TEST_MODE:'local-only',RAISING_TEST_HISTORY:{symbol:'BTCUSD',bars:bars()}};
  delete env.RAISING_TEST_HISTORY.bars[40].high;
  assert.equal((await call(env,'sessions',{})).status,422);
});
test('short positions lock collateral and close at adverse next open with both fees',async t=>{
  const env={...await setup(t),RAISING_TEST_MODE:'local-only',RAISING_TEST_HISTORY:{symbol:'BTCUSD',bars:bars()}};
  let s=await (await call(env,'sessions',{})).json();
  s=await (await call(env,`sessions/${s.id}/actions`,{action:'SELL',step:0,idempotency_key:'sell'})).json();
  assert.equal(s.account.side,'SHORT');assert.equal(s.account.cash,8999);assert.equal(s.account.entry_price,130*.9995);
  const qty=s.account.quantity,entry=s.account.entry_price;
  s=await (await call(env,`sessions/${s.id}/actions`,{action:'CLOSE',step:1,idempotency_key:'close'})).json();
  assert.equal(s.account.side,'FLAT');
  assert.ok(Math.abs(s.account.cash-(9999+qty*(entry-135*1.0005)-qty*135*1.0005*.001))<1e-8);
  assert.ok(s.account.max_drawdown>0);
});
test('Kraken closed history validation, family reservation, bounded reward and no fallback',async t=>{
  const env=await setup(t); const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);
  await env.DB.prepare('INSERT INTO raising_points VALUES (?,?,?,?,?)').bind('prior-reward','alice',98,'REWARD',Date.now()).run();
  globalThis.fetch=async()=>{throw Error('offline');};
  assert.equal((await call(env,'sessions',{})).status,503);
  const payload=(list)=>({error:[],result:{XXBTZUSD:list.map(b=>[b.time,String(b.open),String(b.high),String(b.low),String(b.close),'0',String(b.volume),1]),last:1}});
  globalThis.fetch=async()=>Response.json(payload(bars().filter((_,i)=>i!==40)));
  assert.equal((await call(env,'sessions',{})).status,422);
  globalThis.fetch=async()=>Response.json({error:[],result:{XXBTZUSD:[null],last:1}});
  assert.equal((await call(env,'sessions',{})).status,422);
  let fetched='';globalThis.fetch=async url=>{fetched=String(url);return Response.json(payload(bars()));};
  const starts=await Promise.all([call(env,'sessions',{}),call(env,'sessions',{})]);
  let s=await starts[0].json();assert.equal(s.reward_eligible,true);assert.match(fetched,/api.kraken.com.*OHLC/);
  assert.equal((await starts[1].json()).id,s.id);
  assert.equal((await (await call(env,'profile')).json()).active_session_id,s.id);
  for(let step=0;step<12;step++) s=await (await call(env,`sessions/${s.id}/actions`,{action:step?'HOLD':'BUY',step,idempotency_key:`r${step}`})).json();
  assert.equal(s.reward_points,2);
  assert.equal((await (await call(env,'profile')).json()).points,100);
  const replay=await (await call(env,'sessions',{})).json();assert.equal(replay.reward_eligible,false);
  assert.equal((await env.DB.prepare('SELECT COUNT(*) n FROM raising_reservations').first()).n,1);
  const review=await (await call(env,`sessions/${s.id}/review`)).json(); assert.equal(review.demonstrations[0].eligible,true);
  assert.equal(review.demonstrations[0].observation_hash,(await import('../worker/src/raising-core.mjs')).hash?await (await import('../worker/src/raising-core.mjs')).hash(review.demonstrations[0].observation):'');
});
test('historical round keeps future server-only, immutable HOLD labels, next-open fills and separate settlement',async t=>{
  const env={...await setup(t),RAISING_TEST_MODE:'local-only',RAISING_TEST_HISTORY:{symbol:'BTCUSD',bars:bars()}};
  const r=await call(env,'sessions',{}); assert.equal(r?.status,201);
  let s=await r.json(); const id=s.id;
  assert.equal(s.bars.length,30); assert.equal(s.reward_eligible,false);
  assert.equal((await (await call(env,'sessions',{})).json()).id,id);
  assert.equal((await call(env,`sessions/${id}`,undefined,'bob')).status,404);
  assert.equal((await call(env,`sessions/${id}/review`)).status,409);
  assert.equal((await call(env,`sessions/${id}/actions`,{action:'CLOSE',step:0,idempotency_key:'bad'})).status,422);
  const action={action:'BUY',step:0,idempotency_key:'a'};
  const race=await Promise.all([call(env,`sessions/${id}/actions`,action),call(env,`sessions/${id}/actions`,action)]);
  assert.ok(race.every(r=>r.status===200));
  s=await race[0].json(); assert.equal(s.step,1); assert.equal(s.bars.length,35);
  assert.equal(s.account.entry_price,bars()[30].open*1.0005);
  assert.equal((await call(env,`sessions/${id}/actions`,{...action,action:'HOLD'})).status,409);
  assert.equal((await call(env,`sessions/${id}/actions`,{action:'HOLD',step:0,idempotency_key:'stale'})).status,409);
  for(let step=1;step<12;step++) {const r=await call(env,`sessions/${id}/actions`,{action:'HOLD',step,idempotency_key:`a${step}`}); assert.equal(r.status,200); s=await r.json();}
  assert.equal(s.status,'COMPLETED'); assert.equal(s.account.side,'FLAT'); assert.equal(s.reward_points,0);
  const review=await (await call(env,`sessions/${id}/review`)).json();
  assert.equal(review.demonstrations.length,12); assert.equal(review.system_actions.length,1);
  assert.equal(review.demonstrations[11].label,'HOLD'); assert.equal(review.demonstrations[0].visible_bars.length,30);
  assert.equal(review.system_actions[0].source,'SYSTEM'); assert.ok(review.equity_curve.length>=61);
  await assert.rejects(env.DB.prepare("UPDATE raising_demonstrations SET record_json='{}'").run(),/immutable/);
  assert.equal((await (await call(env,'sessions')).json()).sessions.length,1);
  assert.equal((await (await call(env,'profile')).json()).active_session_id,null);
});
test('D1 profile defaults, catalog, atomic idempotent purchase and user isolation',async t=>{
  assert.equal(typeof service.handleRaising,'function');
  const env=await setup(t);
  const p=await (await call(env,'profile')).json();
  assert.equal(p.profile.user_id,'alice'); assert.equal(p.owned.length,4); assert.equal(p.points,0);
  const catalog=await (await call(env,'catalog')).json(); assert.equal(catalog.items.length,12);
  assert.equal((await call(env,'equip',{item_id:'head-crown'})).status,409);
  assert.equal((await call(env,'purchase',{item_id:'head-crown'})).status,409);
  await env.DB.prepare('INSERT INTO raising_points(id,user_id,amount,kind,created_at) VALUES (?,?,?,?,?)').bind('seed','alice',100,'TEST',1).run();
  const results=await Promise.all([call(env,'purchase',{item_id:'head-crown'}),call(env,'purchase',{item_id:'head-crown'})]);
  assert.ok(results.every(r=>r.status===200));
  const updated=await (await call(env,'equip',{item_id:'head-crown'})).json();
  assert.equal(updated.profile.loadout.head,'head-crown');
  assert.equal(updated.points,100-catalog.items.find(i=>i.id==='head-crown').cost);
  assert.equal((await (await call(env,'profile',undefined,'bob')).json()).owned.includes('head-crown'),false);
  await assert.rejects(env.DB.prepare('UPDATE raising_points SET amount=999').run(),/immutable/);
  assert.equal(await call(env,'training'),null);
});