const json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-session-token,idempotency-key','access-control-allow-methods':'GET,POST,OPTIONS','cache-control':'no-store'}});
import {vote,resultHash,ACTIONS} from './colony.mjs';
const b64u=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const fromB64=s=>Uint8Array.from(atob(String(s).replace(/-/g,'+').replace(/_/g,'/')+'==='.slice((s.length+3)%4)),c=>c.charCodeAt(0));
export const PROTOCOL='defly-federation-v1';
export function canonical(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';return '{'+Object.keys(value).filter(k=>value[k]!==undefined).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';}
export async function digest(value){const bytes=new TextEncoder().encode(typeof value==='string'?value:canonical(value));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function verifyManifest(m){
 if(!m||m.protocol!==PROTOCOL||typeof m.fly_id!=='string'||typeof m.owner_public_key!=='object'||typeof m.genesis_model_hash!=='string'||typeof m.checkpoint_hash!=='string'||!Number.isSafeInteger(m.sequence)||m.sequence<0||typeof m.signature!=='string')return 'INVALID_MANIFEST';
 if(m.fly_id!==await digest({owner_public_key:m.owner_public_key,genesis_model_hash:m.genesis_model_hash,nonce:m.nonce}))return 'FLY_ID_MISMATCH';
 try{const key=await crypto.subtle.importKey('jwk',m.owner_public_key,{name:'ECDSA',namedCurve:'P-256'},false,['verify']);const data=JSON.parse(m.signed_payload||'');if(canonical(data)!==canonical({...m,signature:undefined,signed_payload:undefined}))return 'MANIFEST_PAYLOAD_MISMATCH';const ok=await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,fromB64(m.signature),new TextEncoder().encode(m.signed_payload));return ok?null:'INVALID_SIGNATURE';}catch{return 'INVALID_SIGNATURE';}
}
export async function routerInfo(e){return json({protocol:PROTOCOL,router_id:e.ROUTER_ID||'unconfigured-router',public_key:e.ROUTER_PUBLIC_KEY||null,model_manifest_hash:e.FULL_MODEL_MANIFEST_HASH||null,supported_tasks:['replay-v1','colony-vote-v1'],network_mode:'FEDERATED',capabilities:['fly-manifest','colony-submission','cursor-sync']});}
async function peerList(e){return (await e.DB.prepare('SELECT peer_id,base_url,public_key,protocol,last_cursor,last_seen_at,status FROM federation_peers ORDER BY peer_id').all()).results;}
export async function federation(request,e,user,path){
 if(path==='/api/router/info'&&request.method==='GET')return routerInfo(e);
 if(path==='/api/router/peers'){
  if(!user)return json({error:'UNAUTHORIZED'},401);
  if(request.method==='GET')return json({peers:await peerList(e)});
  if(request.method==='POST'){let b;try{b=await request.json();}catch{return json({error:'INVALID_JSON'},400);}if(!/^https:\/\//.test(String(b.base_url||''))&&!/^http:\/\/localhost(:\d+)?$/.test(String(b.base_url||'')))return json({error:'HTTPS_REQUIRED'},422);if(typeof b.peer_id!=='string'||typeof b.public_key!=='object')return json({error:'INVALID_PEER'},422);await e.DB.prepare('INSERT INTO federation_peers(peer_id,base_url,public_key,protocol,last_cursor,last_seen_at,status) VALUES(?,?,?,?,?,?,?) ON CONFLICT(peer_id) DO UPDATE SET base_url=excluded.base_url,public_key=excluded.public_key,protocol=excluded.protocol,last_seen_at=excluded.last_seen_at,status=excluded.status').bind(b.peer_id,b.base_url.replace(/\/$/,''),JSON.stringify(b.public_key),b.protocol||PROTOCOL,b.last_cursor||0,Date.now(),'CONFIGURED').run();return json({peer:(await e.DB.prepare('SELECT * FROM federation_peers WHERE peer_id=?').bind(b.peer_id).first())},201);}
  if(request.method==='DELETE'){const id=new URL(request.url).searchParams.get('peer_id');await e.DB.prepare('DELETE FROM federation_peers WHERE peer_id=?').bind(id||'').run();return json({deleted:true});}
  return json({error:'METHOD_NOT_ALLOWED'},405);
 }
 if(path==='/api/federation/handshake'&&request.method==='POST'){let b;try{b=await request.json();}catch{return json({error:'INVALID_JSON'},400);}if(b.protocol!==PROTOCOL||typeof b.peer_id!=='string')return json({error:'INVALID_HANDSHAKE'},422);return json({protocol:PROTOCOL,router_id:e.ROUTER_ID||'unconfigured-router',public_key:e.ROUTER_PUBLIC_KEY||null,accepted:true,server_time:Date.now()});}
 if(path==='/api/federation/fly-manifest'&&request.method==='POST'){
  if(!user)return json({error:'UNAUTHORIZED'},401);let b;try{b=await request.json();}catch{return json({error:'INVALID_JSON'},400);}const error=await verifyManifest(b);if(error)return json({error},422);if(b.owner_user_id&&b.owner_user_id!==user.id)return json({error:'OWNER_MISMATCH'},403);const prior=await e.DB.prepare('SELECT sequence,checkpoint_hash FROM federation_fly_manifests WHERE fly_id=? ORDER BY sequence DESC LIMIT 1').bind(b.fly_id).first();if(prior&&b.sequence<=prior.sequence)return json({error:'SEQUENCE_CONFLICT',current:prior},409);await e.DB.prepare('INSERT INTO federation_fly_manifests(fly_id,owner_user_id,owner_public_key,genesis_model_hash,checkpoint_hash,parent_checkpoint_hash,sequence,manifest_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(b.fly_id,user.id,JSON.stringify(b.owner_public_key),b.genesis_model_hash,b.checkpoint_hash,b.parent_checkpoint_hash||null,b.sequence,JSON.stringify(b),Date.now()).run();return json({accepted:true,authority:'OWNER_SIGNED',fly_id:b.fly_id,sequence:b.sequence},201);
 }
 if(path==='/api/federation/changes'&&request.method==='GET'){const cursor=Math.max(0,Number(new URL(request.url).searchParams.get('cursor')||0));return json({protocol:PROTOCOL,cursor,manifests:(await e.DB.prepare('SELECT fly_id,checkpoint_hash,parent_checkpoint_hash,sequence,manifest_json,created_at FROM federation_fly_manifests WHERE rowid>? ORDER BY rowid LIMIT 500').bind(cursor).all()).results});}
 if(path==='/api/colony/submissions'&&request.method==='POST'){if(!user)return json({error:'UNAUTHORIZED'},401);let b;try{b=await request.json();}catch{return json({error:'INVALID_JSON'},400);}if(typeof b.task_id!=='string'||typeof b.fly_id!=='string'||typeof b.checkpoint_hash!=='string'||!ACTIONS.includes(b.action))return json({error:'INVALID_SUBMISSION'},422);const id=b.submission_id||crypto.randomUUID();try{await e.DB.prepare('INSERT INTO federation_submissions(submission_id,task_id,fly_id,checkpoint_hash,action,payload_json,created_at) VALUES(?,?,?,?,?,?,?)').bind(id,b.task_id,b.fly_id,b.checkpoint_hash,b.action,JSON.stringify(b),Date.now()).run();}catch(x){if(String(x.message).includes('UNIQUE'))return json({error:'SUBMISSION_EXISTS'},409);throw x;}return json({accepted:true,submission_id:id,authority:'ROUTER_RECORDED'},201);}
 if(path==='/api/colony/vote'&&request.method==='POST'){if(!user)return json({error:'UNAUTHORIZED'},401);let b;try{b=await request.json();}catch{return json({error:'INVALID_JSON'},400);}if(typeof b.task_id!=='string')return json({error:'INVALID_TASK'},422);const rows=(await e.DB.prepare('SELECT fly_id,checkpoint_hash,action FROM federation_submissions WHERE task_id=? ORDER BY created_at,submission_id').bind(b.task_id).all()).results;if(!rows.length)return json({error:'NO_SUBMISSIONS'},409);const result=vote(rows),hash=await resultHash(result);return json({task_id:b.task_id,...result,result_hash:hash,authority:'ROUTER_AGGREGATED'});}
 return null;
}
