import {createLive,receiveLive,tickLive,acceptLive,healthy} from './flydesk-live-core.mjs';
import {marketDecimal,valueAccount} from './flydesk-broker.mjs';
import {chartViews,validateAnalysis} from './flydesk-indicators.mjs';
export class FlydeskLive {
 constructor(ctx,env){this.ctx=ctx;this.env=env;this.socket=null;this.chain=Promise.resolve();this.persistedCount=0;ctx.blockConcurrencyWhile(async()=>{this.state=await ctx.storage.get('state');if(this.state){this.state.records=await Promise.all(Array.from({length:this.state.record_count||0},(_,i)=>ctx.storage.get(`record:${this.state.id}:${i}`)));this.persistedCount=this.state.records.length;}});}
 serial(fn){const result=this.chain.then(fn);this.chain=result.catch(()=>{});return result;}
 async persist(){const values={state:{...this.state,records:undefined,record_count:this.state.records.length}};for(let i=this.persistedCount;i<this.state.records.length;i++)values[`record:${this.state.id}:${i}`]=this.state.records[i];await this.ctx.storage.put(values);this.persistedCount=this.state.records.length;if(['WAITING','ACTIVE'].includes(this.state.status))await this.ctx.storage.setAlarm(Date.now()+500);else{this.socket?.close();this.socket=null;}}
 async connect(){if(this.socket)return;const response=await fetch('https://ws-feed.exchange.coinbase.com',{headers:{Upgrade:'websocket'}}),ws=response.webSocket;if(!ws)throw Error('LIVE_FEED_UNAVAILABLE');ws.accept();this.socket=ws;ws.send(JSON.stringify({type:'subscribe',product_ids:['BTC-USD'],channels:['ticker','heartbeat']}));ws.addEventListener('message',event=>{this.ctx.waitUntil(this.serial(async()=>{try{receiveLive(this.state,JSON.parse(event.data),Date.now());await this.persist();}catch{this.state.status='DATA_INVALID';this.state.error='INVALID_FEED_MESSAGE';await this.persist();}}));});ws.addEventListener('close',()=>{this.socket=null;});ws.addEventListener('error',()=>{this.socket=null;});}
 async candles(){const response=await fetch('https://api.exchange.coinbase.com/products/BTC-USD/candles?granularity=60');if(!response.ok)throw Error('HISTORY_UNAVAILABLE');const rows=await response.json(),now=Date.now()/1000;if(!Array.isArray(rows))throw Error('HISTORY_INVALID');const bars=rows.map(r=>({time:r[0],low:r[1],high:r[2],open:r[3],close:r[4],volume:r[5]})).filter(b=>b.time+60<=now).sort((a,b)=>a.time-b.time).slice(-120);if(bars.length<60||bars.some((b,i)=>!Object.values(b).every(Number.isFinite)||b.low<=0||b.volume<0||b.high<Math.max(b.open,b.close)||b.low>Math.min(b.open,b.close)||(i&&b.time-bars[i-1].time!==60)))throw Error('HISTORY_INCOMPLETE');return bars;}
 async alarm(){return this.serial(async()=>{if(!this.state||!['WAITING','ACTIVE'].includes(this.state.status))return;try{await this.connect();const now=Date.now(),due=this.state.status==='WAITING'?now>=this.state.starts_at:now>=this.state.step_started_at+300000;const bars=due?await this.candles():null;await tickLive(this.state,Date.now(),bars);}catch(e){if(this.state.status==='ACTIVE'){this.state.status='DATA_INVALID';this.state.error=e.message;}}await this.persist();});}
 async fetch(request){return this.serial(async()=>{const user=request.headers.get('x-owner-id'),op=new URL(request.url).pathname;try{
   if(op==='/start'){if(this.state&&['WAITING','ACTIVE'].includes(this.state.status))return this.view();if(this.state)await this.ctx.storage.put('round:'+this.state.id,{...this.state,records:undefined,record_count:this.state.records.length});this.state=createLive(crypto.randomUUID(),user,Date.now());this.persistedCount=0;await this.persist();await this.connect();return this.view();}
   if(!this.state||this.state.user_id!==user)return new Response(JSON.stringify({error:'NOT_FOUND'}),{status:404});
   if(op==='/action'){const body=await request.json();body.analysis=validateAnalysis(body.analysis??{});acceptLive(this.state,body,Date.now());await this.persist();}
   if(op==='/abort'){this.state.status='ABORTED';await this.persist();}
   return this.view();
 }catch(e){return new Response(JSON.stringify({error:e.message,message:e.message}),{status:409,headers:{'content-type':'application/json'}});}});}
 view(){const s=this.state,now=Date.now(),bars=s.snapshot?.bars??[],mark=s.quote?marketDecimal((Number(s.quote.ask)+Number(s.quote.bid))/2):'1',asOf=bars.at(-1)?.time+60;return new Response(JSON.stringify({...s,user_id:undefined,pending:s.pending?{action:s.pending.action,accepted_at:s.pending.accepted_at}:null,account:valueAccount(s.account,mark),market_mode:'LIVE',source:'coinbase_exchange_public',fresh:!!healthy(s,now),server_time:now,answer_deadline:s.step_started_at?s.step_started_at+30000:null,next_decision_at:s.step_started_at?s.step_started_at+300000:s.starts_at,bars,views:bars.length?chartViews(bars,asOf):{},as_of:asOf,observation:s.snapshot?.observation,observation_hash:s.snapshot?.observation_hash,snapshot:undefined,reward_points:0,reward_eligible:false,training_eligible:false,limitation:'Live beta: records retained in the Durable Object; reward and training admission await full replay validation.'}),{headers:{'content-type':'application/json','cache-control':'no-store'}});}
}
