export const ACTIONS=['BUY','SELL','HOLD','CLOSE'];
const clip=x=>Math.max(-1,Math.min(1,Number.isFinite(x)?x:0));
const copy=p=>JSON.parse(JSON.stringify(p));
export function features(prices){const p=prices.map(Number).filter(x=>x>0&&Number.isFinite(x));if(p.length<2)return[0,0,1];const last=p.at(-1),short=p.slice(-3).reduce((a,b)=>a+b,0)/Math.min(3,p.length),long=p.reduce((a,b)=>a+b,0)/p.length,ret=(last-p.at(-2))/p.at(-2),trend=(short-long)/long,vol=Math.sqrt(p.slice(-10).reduce((a,x)=>a+((x-last)/last)**2,0)/Math.min(10,p.length));return[clip(trend*20),clip(ret*30),clip(1-vol*20)]}
export function defaultPolicy(){return{actions:ACTIONS,weights:[[.25,.2,-.04],[-.25,-.2,-.04],[0,0,.08],[0,0,0]],bias:[0,0,.04,0],synapses:Array.from({length:96},()=>1),plasticity:{steps:0,reward_pulses:0,aversive_pulses:0,changed_synapses:0,last_signal:null},version:0,updates:0,rewardTotal:0,corrections:0}}
export function chooseAction(policy,f,mask=[true,true,true]){const rowWeights=policy.weights||[];const logits=ACTIONS.map((_,a)=>{const ws=rowWeights[a]||[0,0,0];return mask[a]?policy.bias[a]+ws.reduce((s,w,i)=>s+w*f[i],0):-1e9}),m=Math.max(...logits),ex=logits.map(x=>Math.exp(x-m)),sum=ex.reduce((a,b)=>a+b,0),probabilities=ex.map(x=>x/sum),idx=logits.indexOf(Math.max(...logits));return{action:ACTIONS[idx],probabilities,logits}}
export function reinforce(policy,f,action,reward,lr=.035){const n=copy(policy),a=ACTIONS.indexOf(action),r=clip(reward);if(a<0)return n;for(let i=0;i<f.length;i++)n.weights[a][i]+=lr*r*f[i];n.bias[a]+=lr*r;n.version++;n.updates=(n.updates||0)+1;n.rewardTotal=(n.rewardTotal||0)+r;return n}
export function correctPolicy(policy,f,source,corrected,lr=.12){let n=reinforce(policy,f,corrected,1,lr);if(source!==corrected)n=reinforce(n,f,source,-.5,lr);n.version=policy.version+1;n.updates=(policy.updates||0)+1;n.corrections=(policy.corrections||0)+1;return n}
export async function policyHash(policy){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(policy)));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
export function rewardFromEquity(before,after){if(!(before>0)||!Number.isFinite(after))return 0;return clip((after-before)/before*100)}
export function plasticitySignal(reward){if(reward>0)return{cell_group:'PAM11',pulse_ms:200,amplitude:20,kind:'REWARD'};if(reward<0)return{cell_group:'PPL101',pulse_ms:200,amplitude:20,kind:'AVERSIVE'};return{cell_group:null,pulse_ms:0,amplitude:0,kind:'NONE'}}
export function applyPlasticity(policy,eligibility,reward){const n=copy(policy),sig=plasticitySignal(reward);if(!sig.cell_group)return n;const sign=reward>0?1:-1,rate=.001;n.synapses=n.synapses.map((w,i)=>Math.max(.1,Math.min(2,w+sign*rate*(Number(eligibility[i%eligibility.length])||0))));const changed=n.synapses.filter((w,i)=>w!==policy.synapses[i]).length;n.plasticity={...n.plasticity,steps:n.plasticity.steps+1,reward_pulses:n.plasticity.reward_pulses+(reward>0?1:0),aversive_pulses:n.plasticity.aversive_pulses+(reward<0?1:0),changed_synapses:n.plasticity.changed_synapses+changed,last_signal:`${sig.cell_group}_${sig.kind}`};return n}
export async function plasticityHash(policy){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(policy.synapses)));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
