export function initLiveDesk({root,api,onObservation,onSelect=()=>{},isVisible=()=>true,getAnalysis=()=>({})}) {
 const section=document.createElement('details');section.className='live-desk';section.innerHTML='<summary>Live paper desk · Expand</summary><p>Coinbase BTC-USD · live public quotes, simulated fills · one decision every five minutes, 30-second response window</p><button data-live="start">Start live round</button><button data-live="abort">End live round</button><div><button data-live="BUY">Buy one lot</button><button data-live="SELL">Sell one lot</button><button data-live="HOLD">Hold</button><button data-live="SKIP">Skip</button></div><p role="status">Not started · live beta does not award points or enter training yet</p><button data-export>Export live record</button>';root.prepend(section);
 const status=section.querySelector('[role=status]');let state=null,busy=false,pending=null;
 function render(){const active=state?.status==='ACTIVE',remaining=state?.answer_deadline?Math.max(0,Math.ceil((state.answer_deadline-state.server_time)/1000)):0;for(const b of section.querySelectorAll('[data-live]')){const op=b.dataset.live;if(['BUY','SELL','HOLD','SKIP'].includes(op))b.disabled=busy||!active||!state.fresh||remaining===0||!!state.pending||state.records?.some(r=>r.step===state.step)||(op!=='SKIP'&&!state.observation?.action_mask.includes(op));else b.disabled=busy;}if(state){status.textContent=`${state.status} · ${state.fresh?'Market fresh':'Waiting for fresh market data'} · Step ${Math.min(12,state.step+1)} / 12 steps · remaining ${remaining} seconds · ${state.error||'points and training eligibility pending full validation'}`;if(state.status==='WAITING')status.textContent+=' · first decision '+new Date(state.starts_at).toLocaleTimeString('en-US');}}
 async function load(){if(busy)return;try{const s=await api('/api/flydesk/live/state');state=s;if(s.bars?.length&&isVisible())onObservation({...s,total_steps:12,provenance:{provider:s.source,synthetic:false},analysis:getAnalysis()});render();}catch(e){if(e.status!==404)status.textContent='Live service:'+e.message;}}
 section.onclick=async e=>{const op=e.target.closest('[data-live]')?.dataset.live;if(!op)return;busy=true;render();try{if(['start','abort'].includes(op)){if(op==='start')await onSelect();state=await api('/api/flydesk/live/'+op,{method:'POST',body:{}});pending=null;}else{if(pending&&pending.action!==op)throw Error('Retry the unconfirmed action first');pending??={action:op,step:state.step,idempotency_key:crypto.randomUUID(),analysis:getAnalysis()};state=await api('/api/flydesk/live/action',{method:'POST',body:pending});pending=null;}render();}catch(err){status.textContent=err.message;}finally{busy=false;render();}};
 section.querySelector('[data-export]').onclick=()=>{if(!state)return;const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`live-${state.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const timer=setInterval(()=>{if(state&&['WAITING','ACTIVE'].includes(state.status))load();},1000);load();return {destroy:()=>clearInterval(timer)};
}
