export function initLiveDesk({root,api,onObservation,onSelect=()=>{},isVisible=()=>true,getAnalysis=()=>({})}) {
 const section=document.createElement('details');section.className='live-desk';section.innerHTML='<summary>实时模拟盘 · 点击展开</summary><p>Coinbase BTC-USD · 真实公共行情，站内模拟成交 · 每五分钟一次判断，30 秒作答</p><button data-live="start">开始实时回合</button><button data-live="abort">结束实时回合</button><div><button data-live="BUY">买一档</button><button data-live="SELL">卖一档</button><button data-live="HOLD">不动</button><button data-live="SKIP">跳过</button></div><p role="status">尚未开始 · 实时测试版暂不发积分或进入训练</p><button data-export>导出实时记录</button>';root.prepend(section);
 const status=section.querySelector('[role=status]');let state=null,busy=false,pending=null;
 function render(){const active=state?.status==='ACTIVE',remaining=state?.answer_deadline?Math.max(0,Math.ceil((state.answer_deadline-state.server_time)/1000)):0;for(const b of section.querySelectorAll('[data-live]')){const op=b.dataset.live;if(['BUY','SELL','HOLD','SKIP'].includes(op))b.disabled=busy||!active||!state.fresh||remaining===0||!!state.pending||state.records?.some(r=>r.step===state.step)||(op!=='SKIP'&&!state.observation?.action_mask.includes(op));else b.disabled=busy;}if(state){status.textContent=`${state.status} · ${state.fresh?'行情正常':'等待新鲜行情'} · 第 ${Math.min(12,state.step+1)} / 12 步 · 剩余 ${remaining} 秒 · ${state.error||'积分及训练资格待完整验证'}`;if(state.status==='WAITING')status.textContent+=' · 首次判断 '+new Date(state.starts_at).toLocaleTimeString();}}
 async function load(){if(busy)return;try{const s=await api('/api/flydesk/live/state');state=s;if(s.bars?.length&&isVisible())onObservation({...s,total_steps:12,provenance:{provider:s.source,synthetic:false},analysis:getAnalysis()});render();}catch(e){if(e.status!==404)status.textContent='实时服务：'+e.message;}}
 section.onclick=async e=>{const op=e.target.closest('[data-live]')?.dataset.live;if(!op)return;busy=true;render();try{if(['start','abort'].includes(op)){if(op==='start')await onSelect();state=await api('/api/flydesk/live/'+op,{method:'POST',body:{}});pending=null;}else{if(pending&&pending.action!==op)throw Error('请先重试待确认的动作');pending??={action:op,step:state.step,idempotency_key:crypto.randomUUID(),analysis:getAnalysis()};state=await api('/api/flydesk/live/action',{method:'POST',body:pending});pending=null;}render();}catch(err){status.textContent=err.message;}finally{busy=false;render();}};
 section.querySelector('[data-export]').onclick=()=>{if(!state)return;const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`live-${state.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const timer=setInterval(()=>{if(state&&['WAITING','ACTIVE'].includes(state.status))load();},1000);load();return {destroy:()=>clearInterval(timer)};
}
