// Server supplies every candle and indicator. This module only maps data to pixels.
export function createDeskChart(canvas,{save=async()=>{}}={}) {
  const toolbar=document.createElement('div');toolbar.className='desk-chart-toolbar';
  toolbar.innerHTML='<label>周期 <select aria-label="图表周期"><option value="60">1 分钟</option><option value="300">5 分钟</option><option value="3600">1 小时</option></select></label><button data-tool="crosshair">十字线</button><button data-tool="horizontal_line">水平线</button><button data-tool="trend_line">趋势线</button><button data-tool="rectangle">矩形</button><button data-tool="select">移动图形</button><button data-edit="delete">删除选中</button><button data-edit="undo">撤销</button><button data-edit="redo">重做</button><button data-edit="reset">重置缩放</button><span role="status"></span>';
  canvas.before(toolbar);canvas.style.touchAction='none';canvas.setAttribute('aria-label','K线 成交量 RSI MACD 和分析图形');
  const select=toolbar.querySelector('select'),status=toolbar.querySelector('[role=status]');
  let session=null,analysis={timeframe:60,drawings:[]},tool='crosshair',pending=null,selected=null,drag=null,undo=[],redo=[],cursor=null,limit=120,offset=0,saveChain=Promise.resolve();
  const clone=x=>JSON.parse(JSON.stringify(x));
  const current=()=>session?.views?.[analysis.timeframe];
  function geometry(){const bars=current()?.bars??[],end=Math.max(1,bars.length-offset),start=Math.max(0,end-limit),visible=bars.slice(start,end),prices=visible.flatMap(b=>[b.low,b.high]);const low=Math.min(...prices),high=Math.max(...prices),pad=(high-low||high*.01||1)*.1;return {bars,visible,start,end,low:low-pad,high:high+pad,w:canvas.width,h:canvas.height,left:12,right:canvas.width-75,top:20,bottom:canvas.height*.53};}
  const xOf=(time,g)=>g.left+(time-(g.visible[0]?.time??0))/(Number(analysis.timeframe)*Math.max(1,g.visible.length+5))*(g.right-g.left);
  const yOf=(price,g)=>g.bottom-(price-g.low)/(g.high-g.low)*(g.bottom-g.top);
  function point(e){const r=canvas.getBoundingClientRect(),g=geometry(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height;return {x,y,time:(g.visible[0]?.time??0)+(x-g.left)/(g.right-g.left)*Number(analysis.timeframe)*Math.max(1,g.visible.length+5),price:g.low+(g.bottom-y)/(g.bottom-g.top)*(g.high-g.low),projection:x>xOf(g.visible.at(-1)?.time??0,g)};}
  function persist(){const snapshot=clone(analysis);saveChain=saveChain.catch(()=>{}).then(()=>save(snapshot));saveChain.then(()=>{status.textContent='分析已保存';},e=>{status.textContent='保存失败：'+e.message;});}
  function changed(before){undo.push(before);if(undo.length>100)undo.shift();redo=[];persist();render();}
  function line(ctx,values,g,color,yMap){ctx.strokeStyle=color;ctx.lineWidth=1.4;ctx.beginPath();let active=false;for(let i=g.start;i<g.end;i++){const v=values?.[i];if(v==null){active=false;continue;}const x=xOf(g.bars[i].time,g),y=yMap(v);if(active)ctx.lineTo(x,y);else ctx.moveTo(x,y);active=true;}ctx.stroke();}
  function render(){const ctx=canvas.getContext('2d'),g=geometry();ctx.fillStyle='#101719';ctx.fillRect(0,0,g.w,g.h);if(!g.visible.length)return;ctx.font='12px sans-serif';ctx.fillStyle='#bdff32';ctx.fillText('模拟行情 · SMA20 / SMA50 · RSI14 · MACD',12,14);ctx.lineWidth=1;
    for(let i=0;i<5;i++){const y=g.top+(g.bottom-g.top)*i/4;ctx.strokeStyle='#2b383c';ctx.beginPath();ctx.moveTo(g.left,y);ctx.lineTo(g.right,y);ctx.stroke();ctx.fillStyle='#a4b7b8';ctx.fillText((g.high-(g.high-g.low)*i/4).toFixed(2),g.right+4,y+4);}
    const width=Math.max(1,(g.right-g.left)/(g.visible.length+5)*.65),maxVolume=Math.max(1,...g.visible.map(b=>b.volume));
    for(const b of g.visible){const x=xOf(b.time,g),color=b.close>=b.open?'#72d9b1':'#f17e88';ctx.strokeStyle=color;ctx.fillStyle=color;ctx.globalAlpha=b.is_partial?.5:1;ctx.beginPath();ctx.moveTo(x,yOf(b.high,g));ctx.lineTo(x,yOf(b.low,g));ctx.stroke();ctx.fillRect(x-width/2,Math.min(yOf(b.open,g),yOf(b.close,g)),width,Math.max(1,Math.abs(yOf(b.open,g)-yOf(b.close,g))));ctx.fillRect(x-width/2,g.h*.67-b.volume/maxVolume*g.h*.10,width,b.volume/maxVolume*g.h*.10);ctx.globalAlpha=1;}
    const ind=current().indicators;line(ctx,ind.sma20,g,'#e5c16c',v=>yOf(v,g));line(ctx,ind.sma50,g,'#a897ee',v=>yOf(v,g));line(ctx,ind.rsi14,g,'#85b8f1',v=>g.h*.82-v/100*g.h*.12);
    const macd=[...(ind.macd||[]).slice(g.start,g.end),...(ind.signal||[]).slice(g.start,g.end)].filter(v=>v!==null),max=Math.max(.00001,...macd.map(Math.abs));line(ctx,ind.macd,g,'#e5c16c',v=>g.h*.9-v/max*g.h*.06);line(ctx,ind.signal,g,'#a897ee',v=>g.h*.9-v/max*g.h*.06);
    ctx.fillStyle='#a4b7b8';ctx.fillText('VOL',12,g.h*.59);ctx.fillText('RSI 14',12,g.h*.71);ctx.fillText('MACD 12 / 26 / 9',12,g.h*.85);ctx.fillText(new Date(g.visible[0].time*1000).toISOString().slice(5,16).replace('T',' ')+' UTC',12,g.h-5);
    for(const d of analysis.drawings){const [a,b]=d.anchors;ctx.strokeStyle=d.id===selected?'#fff':'#f0cb62';ctx.lineWidth=d.id===selected?3:2;ctx.beginPath();if(d.tool==='horizontal_line'){ctx.moveTo(g.left,yOf(a.price,g));ctx.lineTo(g.right,yOf(a.price,g));}else if(d.tool==='rectangle'){ctx.rect(xOf(a.time,g),yOf(a.price,g),xOf(b.time,g)-xOf(a.time,g),yOf(b.price,g)-yOf(a.price,g));}else{ctx.moveTo(xOf(a.time,g),yOf(a.price,g));ctx.lineTo(xOf(b.time,g),yOf(b.price,g));}ctx.stroke();}
    if(cursor){ctx.strokeStyle='#74888c';ctx.lineWidth=1;ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(cursor.x,g.top);ctx.lineTo(cursor.x,g.bottom);ctx.moveTo(g.left,cursor.y);ctx.lineTo(g.right,cursor.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#fff';ctx.fillText(cursor.price.toFixed(2),Math.min(cursor.x+8,g.w-90),Math.max(35,cursor.y-8));}
  }
  select.onchange=()=>{const before=clone(analysis);analysis.timeframe=Number(select.value);offset=0;changed(before);};
  toolbar.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tool){tool=b.dataset.tool;pending=null;status.textContent=tool==='crosshair'?'滚轮缩放，Shift＋滚轮平移':tool==='select'?'拖动图形锚点':tool==='horizontal_line'?'点击设置水平线':'点击两个锚点';return;}const edit=b.dataset.edit;if(edit==='reset'){limit=120;offset=0;}if(edit==='undo'&&undo.length){redo.push(clone(analysis));analysis=undo.pop();persist();}if(edit==='redo'&&redo.length){undo.push(clone(analysis));analysis=redo.pop();persist();}if(edit==='delete'&&selected){const before=clone(analysis);analysis.drawings=analysis.drawings.filter(d=>d.id!==selected);selected=null;changed(before);}select.value=analysis.timeframe;render();};
  canvas.onpointerdown=e=>{if(!session||session.status==='REVIEW')return;const p=point(e),g=geometry();if(p.y>g.bottom||p.price<=0)return;canvas.setPointerCapture?.(e.pointerId);
    if(tool==='select'){const d=analysis.drawings.find(d=>d.anchors.some(a=>Math.hypot(xOf(a.time,g)-p.x,yOf(a.price,g)-p.y)<20)||(d.tool==='horizontal_line'&&Math.abs(yOf(d.anchors[0].price,g)-p.y)<10));selected=d?.id??null;if(d)drag={before:clone(analysis),id:d.id,start:p,anchors:clone(d.anchors)};render();return;}
    if(tool==='crosshair')return;const anchor={time:p.time,price:p.price,projection:p.projection};if(tool!=='horizontal_line'&&!pending){pending=anchor;status.textContent='选择第二个锚点';return;}const before=clone(analysis);analysis.drawings.push({id:crypto.randomUUID(),tool,anchors:tool==='horizontal_line'?[anchor]:[pending,anchor]});pending=null;changed(before);
  };
  canvas.onpointermove=e=>{if(!session)return;cursor=point(e);if(drag){const d=analysis.drawings.find(d=>d.id===drag.id);d.anchors=drag.anchors.map(a=>({...a,time:a.time+cursor.time-drag.start.time,price:Math.max(.00000001,a.price+cursor.price-drag.start.price),projection:a.time+cursor.time-drag.start.time>=session.as_of}));}render();};
  canvas.onpointerup=()=>{if(drag){const before=drag.before;drag=null;changed(before);}};canvas.onpointerleave=()=>{cursor=null;render();};
  canvas.addEventListener('wheel',e=>{e.preventDefault();if(e.shiftKey)offset=Math.max(0,Math.min((current()?.bars.length??0)-5,offset+Math.sign(e.deltaY)*5));else limit=Math.max(10,Math.min(1000,limit+Math.sign(e.deltaY)*10));render();},{passive:false});
  return {setSession(s){if(s.id!==session?.id){analysis=clone(s.analysis||{timeframe:60,drawings:[]});undo=[];redo=[];offset=0;select.value=analysis.timeframe;}session=s;for(const b of toolbar.querySelectorAll('button,select'))b.disabled=s.status==='REVIEW';toolbar.hidden=!s.views;canvas.height=520;render();},async flush(){await saveChain;},getAnalysis:()=>clone(analysis),render,setVisible(v){toolbar.hidden=!v;}};
}
